"""
Modus — Insights Engine
================================
Three background tasks that compute analytics from existing usage data.

All computation runs inside the existing FastAPI process on the async event
loop. No separate process, no ML library, no message queue.

Algorithms
----------
Anomaly detection:
    Z-score = (actual - mean) / std_dev over a configurable baseline window.
    Baseline computed from daily usage_aggregates (already maintained by the
    aggregator). Pure SQL arithmetic — no scipy, no sklearn.

Spend forecasting:
    Ordinary least squares linear regression over last N days of daily totals.
    OLS in pure Python (4 lines of arithmetic). Extrapolates to EOM, EOQ, EOY.
    R² included as confidence signal.

Model recommendations:
    Identifies apps where high-volume calls go to expensive models with low
    average output tokens (signal of over-provisioning). Computes monthly
    savings delta using the SDK's pricing table. No ML required.

Claude API usage
----------------
OFF by default. Natural-language explanations are generated by Anthropic only
when BOTH (a) the operator sets the relevant system setting to "true"
(insights.anomaly.ai_explanations, insights.recommendations.ai_text,
insights.efficiency.ai_text) AND (b) an Anthropic API key is configured
(MODUS_ASSISTANT_PROVIDER=anthropic + MODUS_ASSISTANT_API_KEY). Otherwise no
request is made and deterministic built-in text is used. Results are cached on
the database row — never regenerated for the same event.

Estimated API cost: <$0.01 per anomaly explanation, <$0.02 per recommendation.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Optional
from urllib import request as urllib_request

from sqlalchemy import text

from orchestrator.db.models import (
    AnomalyEvent, App, OptimizationRecommendation,
    SpendForecast, SystemSetting,
)
from orchestrator.db.session import _session_factory, sqlite_dt

logger = logging.getLogger(__name__)


# ── Settings helper ────────────────────────────────────────────────────────────

_DEFAULTS: dict[str, str] = {
    "task.anomaly_scan.enabled":            "true",
    "task.anomaly_scan.interval_seconds":   "300",
    "task.forecast.enabled":                "true",
    "task.forecast.interval_seconds":       "21600",
    "task.recommendations.enabled":         "true",
    "task.recommendations.interval_seconds":"86400",
    "insights.anomaly.zscore_threshold":    "3.0",
    "insights.anomaly.baseline_days":       "14",
    # AI-written text is OFF by default: enabling any of these makes the
    # orchestrator send anomaly / usage context to api.anthropic.com, and it
    # only does so when an Anthropic key is also configured
    # (MODUS_ASSISTANT_PROVIDER=anthropic + MODUS_ASSISTANT_API_KEY).
    "insights.anomaly.ai_explanations":     "false",
    "insights.recommendations.ai_text":     "false",
    "insights.efficiency.ai_text":          "false",
    "insights.executive.ai_narrative":      "false",
    "task.report_scheduler.enabled":        "true",
    "task.report_scheduler.interval_seconds": "300",
}


async def get_setting(db, key: str) -> str:
    """Read a setting from system_settings, falling back to built-in defaults."""
    row = await db.get(SystemSetting, key)
    if row is not None:
        return row.value
    return _DEFAULTS.get(key, "")


async def get_setting_int(db, key: str, default: int = 0) -> int:
    val = await get_setting(db, key)
    try:
        return int(val)
    except (ValueError, TypeError):
        return default


async def get_setting_float(db, key: str, default: float = 0.0) -> float:
    val = await get_setting(db, key)
    try:
        return float(val)
    except (ValueError, TypeError):
        return default


async def get_setting_bool(db, key: str, default: bool = False) -> bool:
    val = await get_setting(db, key)
    return val.lower() in ("true", "1", "yes", "on")


# ── Claude API helper ──────────────────────────────────────────────────────────

def _anthropic_api_key() -> str:
    """The Anthropic key the operator configured for AI features, or "".

    Reuses the assistant configuration (the same place the in-app assistant
    reads its key): the key counts only when MODUS_ASSISTANT_PROVIDER is
    ``anthropic``. There is deliberately no environment-variable fallback, so
    nothing is sent anywhere unless the operator configured it.
    """
    from orchestrator.core.config import get_settings

    cfg = get_settings()
    if (cfg.assistant_provider or "").lower().strip() != "anthropic":
        return ""
    return (cfg.assistant_api_key or "").strip()


_warned_no_key = False


def _claude_generate(system: str, user: str, max_tokens: int, api_key: str) -> Optional[str]:
    """
    Synchronous Anthropic Messages API call. Run via asyncio.to_thread().
    Returns None on any error (after logging a warning) -- callers fall back
    to deterministic text.
    """
    try:
        payload = json.dumps({
            "model": "claude-haiku-4-5-20251001",  # cheapest model -- explanations only
            "max_tokens": max_tokens,
            "system": system,
            "messages": [{"role": "user", "content": user}],
        }).encode()

        req = urllib_request.Request(
            "https://api.anthropic.com/v1/messages",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        with urllib_request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode())
            blocks = data.get("content", [])
            return next((b["text"] for b in blocks if b.get("type") == "text"), None)
    except Exception as exc:
        # Never log the request (it carries the key header) -- just the cause.
        logger.warning(
            "Anthropic call for AI insight text failed (%s: %s); using built-in text",
            type(exc).__name__, exc,
        )
        return None


async def _ai_explain(system: str, user: str, max_tokens: int = 300) -> Optional[str]:
    """
    Produce explanation text. The only outbound call in this module, and it
    is opt-in twice over: callers invoke it only when the operator enabled the
    relevant ``insights.*`` setting (all default off), and it sends nothing
    unless an Anthropic API key is configured. Otherwise -- or if the call
    fails -- the deterministic built-in text is returned.
    """
    global _warned_no_key
    api_key = _anthropic_api_key()
    if not api_key:
        if not _warned_no_key:
            _warned_no_key = True
            logger.warning(
                "AI insight text is enabled but no Anthropic API key is configured "
                "(set MODUS_ASSISTANT_PROVIDER=anthropic and MODUS_ASSISTANT_API_KEY); "
                "using built-in text and making no outbound call"
            )
        return _fallback_explain(user)
    result = await asyncio.to_thread(_claude_generate, system, user, max_tokens, api_key)
    if result is not None:
        return result
    return _fallback_explain(user)


def _fallback_explain(context: str) -> str:
    """
    Zero-cost deterministic fallback when AI text is unavailable.
    Returns a simple template-based explanation from the context string.
    """
    if "anomaly" in context.lower() or "z-score" in context.lower():
        return "Spend anomaly detected — usage significantly exceeds the historical baseline. Review recent activity."
    if "recommend" in context.lower() or "switch" in context.lower():
        return "Consider switching to a cheaper model for this workload — output token usage suggests simple tasks."
    return "Analysis generated without AI — configure an Anthropic key and enable the insights AI settings for detailed explanations."


# ── Anomaly detection ──────────────────────────────────────────────────────────

async def run_anomaly_scan() -> None:
    """
    Scan for statistical anomalies across all teams.

    For each (team, app, metric) combination:
      1. Compute mean and std_dev from the last N days of daily aggregates
      2. Compute the last-1-hour actual value from hourly aggregates
      3. If z_score >= threshold, create an AnomalyEvent
      4. If AI explanations are enabled and no explanation exists, generate one

    NOTE: Requires PostgreSQL (uses STDDEV_POP, date_trunc). Skipped on SQLite.

    Safe to run multiple times — deduplicates by checking for existing events
    in the same 1-hour window.
    """
    if _session_factory is None:
        return
    from orchestrator.core.config import settings as _cfg
    if _cfg.is_sqlite:
        logger.debug("Anomaly scan skipped (SQLite — requires PostgreSQL)")
        return

    start = time.perf_counter()
    events_fired = 0

    try:
        async with _session_factory() as db:
            zscore_threshold = await get_setting_float(
                db, "insights.anomaly.zscore_threshold", 3.0
            )
            baseline_days = await get_setting_int(
                db, "insights.anomaly.baseline_days", 14
            )
            ai_enabled = await get_setting_bool(
                db, "insights.anomaly.ai_explanations", False
            )

            now = datetime.now(timezone.utc)
            baseline_start = now - timedelta(days=baseline_days)
            current_window_start = now - timedelta(hours=1)

            # Compute per-app daily cost baseline (mean + std_dev)
            baseline_q = await db.execute(text("""
                SELECT
                    app_id,
                    team_id,
                    'cost' AS metric,
                    AVG(total_cost)                         AS mean_val,
                    STDDEV_POP(total_cost)                  AS std_val,
                    COUNT(*)                                AS sample_count
                FROM usage_aggregates
                WHERE granularity = 'daily'
                  AND period_start >= :baseline_start
                  AND period_start < date_trunc('day', NOW() AT TIME ZONE 'UTC')
                GROUP BY app_id, team_id
                HAVING COUNT(*) >= 3
            """), {"baseline_start": sqlite_dt(baseline_start)})

            baselines = {
                (str(r.app_id), str(r.team_id), r.metric): {
                    "mean": float(r.mean_val or 0),
                    "std":  float(r.std_val or 0),
                    "n":    r.sample_count,
                }
                for r in baseline_q.all()
            }

            # Compute current-hour actual values
            current_q = await db.execute(text("""
                SELECT
                    app_id,
                    team_id,
                    SUM(total_cost)   AS cost_actual,
                    SUM(call_count)   AS calls_actual
                FROM usage_aggregates
                WHERE granularity = 'hourly'
                  AND period_start >= :window_start
                GROUP BY app_id, team_id
            """), {"window_start": sqlite_dt(current_window_start)})

            current_by_app: dict[tuple, dict] = {}
            for r in current_q.all():
                current_by_app[(str(r.app_id), str(r.team_id))] = {
                    "cost":  float(r.cost_actual or 0),
                    "calls": float(r.calls_actual or 0),
                }

            # Check for existing events in this hour window (dedup)
            existing_q = await db.execute(text("""
                SELECT app_id, metric
                FROM anomaly_events
                WHERE detected_at >= :window_start
            """), {"window_start": sqlite_dt(current_window_start)})
            already_fired = {
                (str(r.app_id), r.metric) for r in existing_q.all()
            }

            for (app_id, team_id, metric), baseline in baselines.items():
                if baseline["std"] < 0.0001:
                    continue  # No variance — skip

                actual_data = current_by_app.get((app_id, team_id), {})
                actual = actual_data.get(metric, 0.0)

                # Normalise hourly actual to daily-equivalent for comparison
                hour_of_day = now.hour + 1  # hours elapsed today
                daily_equivalent = (actual / max(hour_of_day, 1)) * 24

                z = (daily_equivalent - baseline["mean"]) / baseline["std"]

                if z < zscore_threshold:
                    continue

                if (app_id, metric) in already_fired:
                    continue

                # Determine severity
                if z >= 6.0:
                    severity = "critical"
                elif z >= 4.5:
                    severity = "high"
                elif z >= zscore_threshold + 0.5:
                    severity = "medium"
                else:
                    severity = "low"

                # Fetch app name for AI context
                app_row = await db.get(App, app_id)
                app_name = app_row.app_name if app_row else app_id

                # Create the anomaly event
                event_id = __import__("uuid").uuid4().__str__()
                event = AnomalyEvent(
                    id=event_id,
                    team_id=team_id,
                    app_id=app_id,
                    metric=metric,
                    severity=severity,
                    z_score=Decimal(str(round(z, 4))),
                    baseline_value=Decimal(str(round(baseline["mean"], 8))),
                    actual_value=Decimal(str(round(daily_equivalent, 8))),
                    window_hours=1,
                    metadata_={
                        "baseline_std":  round(baseline["std"], 8),
                        "baseline_days": baseline_days,
                        "sample_count":  baseline["n"],
                        "raw_actual_1h": round(actual, 8),
                    },
                )
                db.add(event)
                await db.flush()

                # Generate AI explanation if enabled
                if ai_enabled and severity in ("high", "critical"):
                    explanation = await _ai_explain(
                        system=(
                            "You are a cost analysis assistant. Write one concise sentence "
                            "(max 25 words) explaining an AI spend anomaly. Be specific and "
                            "actionable. No markdown, no bullet points."
                        ),
                        user=(
                            f"App '{app_name}' has a cost anomaly: "
                            f"z-score={z:.1f}, severity={severity}. "
                            f"14-day daily average: ${baseline['mean']:.4f}. "
                            f"Current hourly rate annualised to ${daily_equivalent:.4f}/day. "
                            f"Provide one sentence explanation."
                        ),
                        max_tokens=80,
                    )
                    if explanation:
                        event.ai_explanation = explanation.strip()

                events_fired += 1
                logger.info(
                    "Anomaly detected",
                    extra={
                        "app_id": app_id, "metric": metric,
                        "severity": severity, "z_score": round(z, 2),
                    },
                )

            await db.commit()

        elapsed = time.perf_counter() - start
        logger.debug(
            "Anomaly scan complete",
            extra={"events_fired": events_fired, "duration_ms": round(elapsed * 1000)},
        )

    except Exception as exc:
        logger.error("Anomaly scan failed", exc_info=exc)


# ── Spend forecasting ──────────────────────────────────────────────────────────

def _ols_forecast(
    xs: list[float], ys: list[float]
) -> tuple[float, float, float]:
    """
    Ordinary Least Squares linear regression.
    Returns (slope, intercept, r_squared).
    Pure Python — no numpy, no scipy.
    """
    n = len(xs)
    if n < 2:
        return 0.0, ys[0] if ys else 0.0, 0.0

    mx = sum(xs) / n
    my = sum(ys) / n

    ss_xy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    ss_xx = sum((x - mx) ** 2 for x in xs)

    if ss_xx < 1e-10:
        return 0.0, my, 0.0

    slope = ss_xy / ss_xx
    intercept = my - slope * mx

    # R²
    ss_res = sum((y - (slope * x + intercept)) ** 2 for x, y in zip(xs, ys))
    ss_tot = sum((y - my) ** 2 for y in ys)
    r_sq = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-10 else 0.0

    return slope, intercept, max(0.0, min(1.0, r_sq))


async def run_forecast_update() -> None:
    """
    Compute linear regression spend forecasts for each team and org-wide.
    Writes one SpendForecast row per team per run.
    No external API calls — pure arithmetic.

    NOTE: Requires PostgreSQL (uses date_trunc, ::date cast). Skipped on SQLite.
    """
    if _session_factory is None:
        return
    from orchestrator.core.config import settings as _cfg
    if _cfg.is_sqlite:
        logger.debug("Forecast update skipped (SQLite — requires PostgreSQL)")
        return

    start = time.perf_counter()

    try:
        async with _session_factory() as db:
            now = datetime.now(timezone.utc)
            basis_days = 28
            window_start = now - timedelta(days=basis_days)
            period_label = now.strftime("%Y-%m")

            # Days remaining in month / quarter / year
            days_in_month = (
                datetime(now.year, now.month % 12 + 1, 1, tzinfo=timezone.utc)
                if now.month < 12
                else datetime(now.year + 1, 1, 1, tzinfo=timezone.utc)
            )
            days_remaining_month = (days_in_month - now).days

            # Fetch daily totals per team
            daily_q = await db.execute(text("""
                SELECT
                    team_id,
                    date_trunc('day', period_start)::date  AS day,
                    SUM(total_cost)                        AS daily_cost
                FROM usage_aggregates
                WHERE granularity = 'daily'
                  AND period_start >= :window_start
                GROUP BY team_id, date_trunc('day', period_start)::date
                ORDER BY team_id, day
            """), {"window_start": sqlite_dt(window_start)})

            # Group by team
            team_days: dict[str, list[tuple[int, float]]] = {}
            for r in daily_q.all():
                tid = str(r.team_id)
                if tid not in team_days:
                    team_days[tid] = []
                team_days[tid].append((r.day.toordinal(), float(r.daily_cost or 0)))

            teams_processed = 0
            for team_id, day_costs in team_days.items():
                if len(day_costs) < 3:
                    continue

                xs = [float(d - day_costs[0][0]) for d, _ in day_costs]
                ys = [c for _, c in day_costs]

                slope, intercept, r_sq = _ols_forecast(xs, ys)

                # MTD actual
                mtd_q = await db.execute(text("""
                    SELECT COALESCE(SUM(total_cost), 0) AS mtd
                    FROM usage_aggregates
                    WHERE team_id = :tid
                      AND granularity = 'daily'
                      AND period_start >= date_trunc('month', NOW() AT TIME ZONE 'UTC')
                """), {"tid": team_id})
                mtd = float((mtd_q.scalar() or 0))

                # Project remaining days
                last_x = xs[-1]
                eom_additional = sum(
                    max(0.0, slope * (last_x + i) + intercept)
                    for i in range(1, days_remaining_month + 1)
                )
                forecast_eom = Decimal(str(round(mtd + eom_additional, 8)))

                # Rough EOQ — project from now to end of quarter
                q_end_month = ((now.month - 1) // 3 + 1) * 3
                q_end = datetime(
                    now.year if q_end_month <= 12 else now.year + 1,
                    q_end_month % 12 or 12, 28, tzinfo=timezone.utc
                )
                days_to_eoq = max(0, (q_end - now).days)
                eoq_additional = sum(
                    max(0.0, slope * (last_x + i) + intercept)
                    for i in range(1, days_to_eoq + 1)
                )
                forecast_eoq = Decimal(str(round(mtd + eoq_additional, 8)))

                # Trend vs same period last month
                prior_start = window_start - timedelta(days=basis_days)
                prior_q = await db.execute(text("""
                    SELECT COALESCE(SUM(total_cost), 0) AS prior
                    FROM usage_aggregates
                    WHERE team_id = :tid
                      AND granularity = 'daily'
                      AND period_start >= :prior_start
                      AND period_start < :window_start
                """), {"tid": team_id, "prior_start": sqlite_dt(prior_start),
                       "window_start": sqlite_dt(window_start)})
                prior_total = float(prior_q.scalar() or 0)
                current_total = sum(ys)
                trend_pct = (
                    Decimal(str(round(
                        ((current_total - prior_total) / prior_total) * 100, 4
                    )))
                    if prior_total > 0.001 else None
                )

                forecast = SpendForecast(
                    team_id=team_id,
                    period_label=period_label,
                    mtd_actual=Decimal(str(round(mtd, 8))),
                    forecast_eom=forecast_eom,
                    forecast_eoq=forecast_eoq,
                    trend_pct=trend_pct,
                    r_squared=Decimal(str(round(r_sq, 4))),
                    basis_days=basis_days,
                )
                db.add(forecast)
                teams_processed += 1

            await db.commit()

        elapsed = time.perf_counter() - start
        logger.info(
            "Forecast update complete",
            extra={"teams": teams_processed, "duration_ms": round(elapsed * 1000)},
        )

    except Exception as exc:
        logger.error("Forecast update failed", exc_info=exc)


# ── Model optimization recommendations ────────────────────────────────────────

# Model tiers: higher number = more expensive
_MODEL_TIERS: dict[str, int] = {
    # Anthropic
    "claude-haiku":  1, "claude-haiku-4":  1,
    "claude-sonnet": 2, "claude-sonnet-4": 2,
    "claude-opus":   3, "claude-opus-4":   3,
    # OpenAI
    "gpt-3.5":     1, "gpt-4o-mini": 1,
    "gpt-4o":      2,
    "o1-mini":     2, "o3-mini": 2,
    "o1":          3, "o3": 3, "gpt-4-5": 3,
    # Google
    "gemini-flash": 1, "gemini-2.0-flash": 1,
    "gemini-pro":   2, "gemini-1.5-pro":   2,
    # Groq
    "llama-3.1-8b":  1, "gemma-7b": 1,
    "llama-3.3-70b": 2, "mixtral":  2,
    # Cohere
    "command-r": 1, "command-r-plus": 2,
    # Mistral
    "mistral-7b": 1, "mixtral-8x7b": 2, "mistral-large": 3,
}

# Keys are matched as PREFIXES in insertion order, so more specific keys must
# come first (e.g. "claude-opus-4-5" before any shorter "claude-opus" key).
_MODEL_SUGGESTIONS: dict[str, str] = {
    # Anthropic downgrades
    "claude-fable-5":       "claude-opus-5",
    "claude-mythos-5":      "claude-opus-5",
    "claude-opus-4-5":      "claude-sonnet-4-5",
    "claude-opus-4-6":      "claude-sonnet-4-6",
    "claude-opus-4-7":      "claude-sonnet-5",
    "claude-opus-4-8":      "claude-sonnet-5",
    "claude-opus-5":        "claude-sonnet-5",
    "claude-sonnet-4-5":    "claude-haiku-4-5",
    "claude-sonnet-4-6":    "claude-haiku-4-5",
    "claude-sonnet-5":      "claude-haiku-4-5",
    # OpenAI downgrades
    "gpt-4-5":    "gpt-4o",
    "gpt-4o":     "gpt-4o-mini",
    "o3":         "o3-mini",
    "o1":         "o1-mini",
    # Google downgrades
    "gemini-1.5-pro": "gemini-2.0-flash",
    # Mistral downgrades
    "mistral-large": "mixtral-8x7b-instruct",
}

# Output token threshold: below this avg suggests simple/classification tasks
_LOW_OUTPUT_TOKEN_THRESHOLD = 256


async def run_recommendation_refresh() -> None:
    """
    Identify apps using expensive models for tasks where cheaper models suffice.

    Heuristic: high call volume + low average output tokens on a premium model
    → likely overprovisioned. Compute savings delta and store recommendation.

    Existing non-dismissed recommendations for the same app+model pair are
    replaced (upsert by deleting old then inserting new).
    """
    if _session_factory is None:
        return

    start = time.perf_counter()
    recs_created = 0

    try:
        async with _session_factory() as db:
            ai_enabled = await get_setting_bool(
                db, "insights.recommendations.ai_text", False
            )

            now = datetime.now(timezone.utc)
            window_start = now - timedelta(days=7)

            # Aggregate by app + model over last 7 days
            usage_q = await db.execute(text("""
                SELECT
                    a.app_id              AS app_uuid,
                    a.team_id             AS team_uuid,
                    a.app_name,
                    ua.model,
                    ua.provider,
                    SUM(ua.call_count)    AS total_calls,
                    SUM(ua.output_tokens) AS total_output_tokens,
                    SUM(ua.total_cost)    AS total_cost_7d,
                    AVG(ua.output_tokens::float / NULLIF(ua.call_count, 0))
                                          AS avg_output_per_call
                FROM usage_aggregates ua
                JOIN apps a ON a.id = ua.app_id
                WHERE ua.granularity = 'daily'
                  AND ua.period_start >= :window_start
                  AND ua.call_count > 0
                GROUP BY a.app_id, a.team_id, a.app_name, ua.model, ua.provider
                HAVING SUM(ua.call_count) >= 100
                ORDER BY SUM(ua.total_cost) DESC
            """), {"window_start": sqlite_dt(window_start)})

            rows = usage_q.all()

            for row in rows:
                model = (row.model or "").lower()
                provider = (row.provider or "").lower()
                avg_out = float(row.avg_output_per_call or 0)
                calls_7d = int(row.total_calls or 0)
                cost_7d = float(row.total_cost_7d or 0)

                # Find a suggested cheaper model
                suggested = None
                for prefix, suggestion in _MODEL_SUGGESTIONS.items():
                    if model.startswith(prefix.lower()):
                        suggested = suggestion
                        break

                if not suggested:
                    continue

                # Only recommend if output tokens suggest simple tasks
                if avg_out > _LOW_OUTPUT_TOKEN_THRESHOLD:
                    continue

                # Compute savings using pricing module
                try:
                    from orchestrator.core.pricing import estimate_cost
                    calls_per_day = calls_7d / 7.0
                    # Estimate with typical token distribution
                    avg_in = 500  # conservative input estimate
                    _, _, cost_current = estimate_cost(
                        provider, model, int(avg_in), int(avg_out)
                    )
                    _, _, cost_suggested = estimate_cost(
                        provider, suggested, int(avg_in), int(avg_out)
                    )
                    savings_per_call = max(0.0, float(cost_current) - float(cost_suggested))
                    monthly_savings = savings_per_call * calls_per_day * 30
                except Exception:
                    # Fallback: estimate 60% savings for major tier drop
                    monthly_savings = cost_7d * (30 / 7) * 0.60

                if monthly_savings < 1.0:
                    continue  # Not worth recommending for < $1/month

                confidence = "high" if avg_out < 100 else "medium"

                # Delete any existing undismissed recommendation for this app+model
                await db.execute(text("""
                    DELETE FROM optimization_recommendations
                    WHERE app_id = :app_id
                      AND current_model = :model
                      AND dismissed_at IS NULL
                      AND applied_at IS NULL
                """), {"app_id": str(row.app_uuid), "model": row.model})

                rec_text = None
                if ai_enabled:
                    rec_text = await _ai_explain(
                        system=(
                            "You are a cost optimization assistant. Write one concise sentence "
                            "(max 30 words) recommending a cheaper AI model. Be specific about "
                            "the savings and why the cheaper model is sufficient. No markdown."
                        ),
                        user=(
                            f"App '{row.app_name}' makes {int(calls_per_day):.0f} calls/day "
                            f"to {row.model} with avg {avg_out:.0f} output tokens. "
                            f"Suggest switching to {suggested}. "
                            f"Estimated monthly savings: ${monthly_savings:.2f}."
                        ),
                        max_tokens=80,
                    )

                rec = OptimizationRecommendation(
                    team_id=str(row.team_uuid),
                    app_id=str(row.app_uuid),
                    current_model=row.model,
                    suggested_model=suggested,
                    provider=provider,
                    call_volume_basis=calls_7d,
                    estimated_monthly_savings=Decimal(str(round(monthly_savings, 8))),
                    confidence=confidence,
                    recommendation_text=rec_text.strip() if rec_text else None,
                )
                db.add(rec)
                recs_created += 1

            await db.commit()

        elapsed = time.perf_counter() - start
        logger.info(
            "Recommendation refresh complete",
            extra={"recommendations": recs_created, "duration_ms": round(elapsed * 1000)},
        )

    except Exception as exc:
        logger.error("Recommendation refresh failed", exc_info=exc)


# ── Prompt Efficiency Auditor ──────────────────────────────────────────────────
#
# Analyses token distribution patterns per app/model to identify structural
# waste without reading prompt content.  Runs on the cold path (background).
#
# What it surfaces:
#   - System prompt overhead: high input_tokens with low variance → fixed cost
#   - Output bloat: disproportionately large output tokens per call
#   - Input/output ratio anomalies: endpoints where input >> output (prompt waste)
#
# Produces PromptEfficiencyInsight rows (stored as OptimizationRecommendation
# with confidence="efficiency_audit" to reuse existing model/UI).

# Threshold: input/output ratio above this = likely system-prompt-heavy
_HIGH_INPUT_RATIO_THRESHOLD = 8.0
# Minimum calls to consider an app/model pair for audit
_MIN_CALLS_FOR_AUDIT = 50
# Minimum input tokens avg to be worth flagging
_MIN_INPUT_TOKENS_AVG = 1000


async def run_prompt_efficiency_audit() -> None:
    """
    Identify apps with structurally inefficient prompt patterns.

    Builds a cost fingerprint per (app, model) from token distribution:
      - avg_input_tokens, stddev_input_tokens → high avg + low stddev = large static prompt
      - avg_output_tokens → low output for high input = overprovisioned context
      - input/output ratio → >8:1 ratio suggests prompt compression opportunity

    Recommendations quantify savings: "Compressing to N tokens saves $X/month."
    """
    if _session_factory is None:
        return

    start = time.perf_counter()
    insights_created = 0

    try:
        async with _session_factory() as db:
            ai_enabled = await get_setting_bool(
                db, "insights.efficiency.ai_text", False
            )

            now = datetime.now(timezone.utc)
            window_start = now - timedelta(days=14)

            # Aggregate token distribution stats per app + model over last 14 days
            stats_q = await db.execute(text("""
                SELECT
                    ur.app_id,
                    a.app_name,
                    ur.team_id,
                    ur.model,
                    ur.provider,
                    COUNT(*)                              AS call_count,
                    AVG(CAST(ur.input_tokens AS FLOAT))   AS avg_input,
                    AVG(CAST(ur.output_tokens AS FLOAT))  AS avg_output,
                    SUM(ur.total_cost)                    AS total_cost_14d,
                    SUM(ur.input_cost)                    AS total_input_cost_14d
                FROM usage_records ur
                JOIN apps a ON a.id = ur.app_id
                WHERE ur.timestamp >= :window_start
                  AND ur.input_tokens IS NOT NULL
                  AND ur.input_tokens > 0
                  AND ur.output_tokens IS NOT NULL
                GROUP BY ur.app_id, a.app_name, ur.team_id, ur.model, ur.provider
                HAVING COUNT(*) >= :min_calls
                   AND AVG(CAST(ur.input_tokens AS FLOAT)) >= :min_input
                ORDER BY SUM(ur.total_cost) DESC
                LIMIT 100
            """), {
                "window_start": sqlite_dt(window_start),
                "min_calls": _MIN_CALLS_FOR_AUDIT,
                "min_input": _MIN_INPUT_TOKENS_AVG,
            })

            rows = stats_q.all()

            for row in rows:
                avg_in = float(row.avg_input or 0)
                avg_out = float(row.avg_output or 1)
                calls = int(row.call_count or 0)
                float(row.total_cost_14d or 0)
                input_cost_14d = float(row.total_input_cost_14d or 0)
                ratio = avg_in / max(avg_out, 1)

                if ratio < _HIGH_INPUT_RATIO_THRESHOLD:
                    continue  # Input/output ratio is reasonable

                # Estimate savings from compressing input by 50-75%
                # (conservative — most system prompts can be compressed 60-80%)
                compression_factor = 0.25  # keep 25% of current input
                input_savings_pct = 1.0 - compression_factor
                monthly_input_savings = (input_cost_14d / 14) * 30 * input_savings_pct

                if monthly_input_savings < 5.0:
                    continue  # Not worth flagging for < $5/month

                calls_per_day = calls / 14.0

                # Delete existing efficiency audit for this app+model
                await db.execute(text("""
                    DELETE FROM optimization_recommendations
                    WHERE app_id = :app_id
                      AND current_model = :model
                      AND confidence = 'efficiency_audit'
                      AND dismissed_at IS NULL
                      AND applied_at IS NULL
                """), {"app_id": str(row.app_id), "model": row.model})

                rec_text = None
                if ai_enabled:
                    rec_text = await _ai_explain(
                        system=(
                            "You are a prompt efficiency advisor. Write one actionable sentence "
                            "(max 40 words) about reducing input token waste. Be specific about "
                            "the numbers. No markdown."
                        ),
                        user=(
                            f"App '{row.app_name}' sends avg {avg_in:.0f} input tokens and "
                            f"gets avg {avg_out:.0f} output tokens per call to {row.model} "
                            f"({calls_per_day:.0f} calls/day, {ratio:.1f}:1 input/output ratio). "
                            f"Input cost: ${input_cost_14d/14*30:.2f}/month. "
                            f"Compressing prompts to ~{avg_in*compression_factor:.0f} tokens "
                            f"saves ~${monthly_input_savings:.2f}/month."
                        ),
                        max_tokens=100,
                    )

                rec = OptimizationRecommendation(
                    team_id=str(row.team_id),
                    app_id=str(row.app_id),
                    current_model=row.model or "unknown",
                    suggested_model=row.model or "unknown",  # same model, just compress
                    provider=row.provider or "unknown",
                    call_volume_basis=calls,
                    estimated_monthly_savings=Decimal(str(round(monthly_input_savings, 8))),
                    confidence="efficiency_audit",
                    recommendation_text=rec_text.strip() if rec_text else (
                        f"System prompt on {row.app_name} averages {avg_in:.0f} input tokens "
                        f"({ratio:.0f}:1 input/output ratio, {calls_per_day:.0f} calls/day). "
                        f"Compressing to ~{avg_in*compression_factor:.0f} tokens saves "
                        f"~${monthly_input_savings:.0f}/month."
                    ),
                )
                db.add(rec)
                insights_created += 1

            await db.commit()

        elapsed = time.perf_counter() - start
        logger.info(
            "Prompt efficiency audit complete",
            extra={"insights": insights_created, "duration_ms": round(elapsed * 1000)},
        )

    except Exception as exc:
        logger.error("Prompt efficiency audit failed", exc_info=exc)


# ── Task loop factory ──────────────────────────────────────────────────────────

async def insights_task_loop(
    task_key: str,
    run_fn,
    default_interval_seconds: int,
) -> None:
    """
    Generic insights task loop.
    Reads interval from system_settings on each iteration — hot-reloadable.
    Checks every 30 seconds whether it's time to run, then sleeps the remainder.

    Args:
        task_key: settings key prefix e.g. "task.anomaly_scan"
        run_fn:   async coroutine function to execute
        default_interval_seconds: fallback if setting not found
    """
    enabled_key  = f"{task_key}.enabled"
    interval_key = f"{task_key}.interval_seconds"

    logger.info("Insights task started: %s (default interval: %ds)",
                task_key, default_interval_seconds)

    last_run: float = 0.0  # epoch seconds of last successful run

    while True:
        try:
            await asyncio.sleep(30)  # check every 30s

            # Read current settings
            if _session_factory is None:
                continue

            async with _session_factory() as db:
                enabled  = await get_setting_bool(db, enabled_key, True)
                interval = await get_setting_int(db, interval_key,
                                                  default_interval_seconds)

            if not enabled:
                continue

            now = time.monotonic()
            if now - last_run < interval:
                continue  # Not time yet

            await run_fn()
            last_run = time.monotonic()

        except asyncio.CancelledError:
            logger.info("Insights task stopping: %s", task_key)
            break
        except Exception as exc:
            logger.error("Insights task error (%s): %s", task_key, exc,
                         exc_info=True)
            # Continue — don't let a task failure kill the loop
